### PR TITLE
remove videoElement on destroy

### PR DESCRIPTION
**Pull request by sagoncalves**

### CODE REVIEW

**Comment by t-mullen** [comment]
Each stream has a unique video element, so keeping a single reference on "this" is not correct.

**Comment by t-mullen** [comment]
Issue is resolved in https://github.com/t-mullen/video-stream-merger/commit/7d3106718eb79319b025c3876be48824f95ce527.

Thanks for the contribution anyways, sorry for not fixing this sooner.

**Comment by sagoncalves** [comment]
Sorry i created a new pull request

**Comment by t-mullen** [comment]
No problem!

**Pull request closed without merging**
