### PR TITLE
Add microbundle as build system and fix package.json

### PR DESCRIPTION
**Pull request by Timebutt**
I couldn't leave it, and created an upgrade for the way this package is built, also because I wanted to experiment with the brilliant [`microbundle`](https://github.com/developit/microbundle) package. So I removed `browserify` in favor of `microbundle`, as it delivers a much better output and transpiles everything to universally useable JS code (if anybody were to add more non `ES5` stuff in the future).

I also corrected the `package.json`, as its `main` file was pointing to the source file, rather than the built file which is why the `patch-package` solution I was using to temporarily fix my issue didn't work. Also added the `files` property, as right now unneeded files were being shipped with the `npm` package, and this helps keep things clean.

### CODE REVIEW

**Comment by Timebutt** [comment]
Hi @t-mullen, wondering if you saw the PR I created? I feel it brings build stability and some nice general improvements, definitely open for discussion.

**Comment by t-mullen** [comment]
Hey @Timebutt. Thanks for the ping. Looks good, I'm interested to give microbundle a try.

**Comment by Timebutt** [comment]
Thanks! `microbundle` is a really interesting project and perfect for a situation like this ;)

**Comment by t-mullen** [comment]
Hey @Timebutt. I notice when I load the new `dist/video-stream-merger.js` bundle I get the error: `Uncaught ReferenceError: module is not defined` for line 3.

```javascript
module.exports = VideoStreamMerger
```

Does microbundle expect some different way of exporting?

**Comment by Timebutt** [comment]
Weird, I'll build the bundle and have a look. The purpose of `microbundle` is to build bundle that can effortlessly be imported anywhere else, so something's wrong.

How are you importing `video-stream-merger` in your application?

**Comment by t-mullen** [comment]
Script tag. It's actually the demo file, `index.html`.

`<script src="dist/video-stream-merger.js"></script>`

**Comment by Timebutt** [comment]
Ok, I'll reproduce and have a look.

**Comment by Timebutt** [comment]
It seems `microbundle` isn't the great solution I thought it was for this repository, as it is not capable of natively generating bundles ready for the browser in the way `Browserify` does. I'm reading up if I can get it to work, and if I can't I'll provide a PR that takes us back to the way it was.

I just wanted to make sure the code is transpiled down into ES5 compatible code, as some of us have to support IE11 unfortunately :/ Will keep you posted!

**Comment by t-mullen** [comment]
Ah that's too bad. You might want to take a look at https://github.com/babel/babelify.

**Comment by Timebutt** [comment]
Jep, exactly what I'm adding right now. I'm playing with some of the configuration to get the best build artifact. New to `Browserify` so need some trial and error ;)

**Comment by Timebutt** [comment]
Created a PR to revert the changes I made earlier, but still maintain ES5 compatibility. Sorry for the small detour, seems like `microbundle` is only a great option when you're shipping for node or `webpack` builds ;)

**Pull request merged**
